### ISSUE TITLE
Use SVG for mobile buttons

### ISSUE THREAD

**Issue by catileptic** [code4romania/teacher-workout-client#42]
Please use the SVG versions for the "[get app from Google Play](https://github.com/code4romania/de-urgenta-client/blob/develop/assets/logo-download-android.svg)" button and the "[get app from app store](https://github.com/code4romania/de-urgenta-client/blob/develop/assets/logo-download-ios.svg)" button

**Comment by andreifilip123** [comment]
I'll take this 👌

**Comment by andreifilip123** [comment]
Since we already have the exact same buttons in the footer, mind if I make that component reusable and use it in the hero as well ?
