### ISSUE TITLE
Secondary feature is mis-aligned

### ISSUE THREAD

**Issue by catileptic** [code4romania/teacher-workout-client#46]
Figma:

<img width="719" alt="Screenshot 2021-06-28 at 12 45 52" src="https://user-images.githubusercontent.com/14028425/123616247-c7e8da00-d80e-11eb-8e7b-2c35e9698fdc.png">

Current alignment via Vercel:

<img width="1191" alt="Screenshot 2021-06-28 at 12 46 23" src="https://user-images.githubusercontent.com/14028425/123616323-da631380-d80e-11eb-80d4-87264effcc69.png">

**Comment by dasilvaluis** [comment]
Taking this bug today
