### ISSUE TITLE
Change cards layout

### ISSUE THREAD

**Issue by radubuciuceanu** [code4romania/teacher-workout-client#58]
## Description

- Change `a-card` to be full-width always.
- Change `b-card` to be full-width always.

![image](https://user-images.githubusercontent.com/39530866/123992532-5eb2c380-d9d4-11eb-8a15-8d80726c9aa2.png)

![image](https://user-images.githubusercontent.com/39530866/123992594-6d00df80-d9d4-11eb-8e53-ea48906bbe64.png)

**Comment by andreifilip123** [comment]
This can be closed since its PR has been merged.

**Comment by radubuciuceanu** [comment]
My issue! 😁
