### ISSUE TITLE
Add Footer component

### ISSUE THREAD

**Issue by catileptic** [code4romania/teacher-workout-client#7]
[The Figma document](https://www.figma.com/file/uLiqrlxmOB5xCppIzmiUXV/Teacher-Workout?node-id=1%3A2) contains the entire UI of the project. 

You can export any image (asset) directly from Figma. [Here's how](https://drive.google.com/file/d/1KJncuAGFvKEo6zrjC9H3O59auITE0q2h/view). 

**Please be mindful of the mobile layout as well. Try to use only Tailwind CSS for styling.**

If you want to work on this Issue, please leave a comment saying you're taking it <3 . 

---

![image](https://user-images.githubusercontent.com/14028425/123398792-983a9780-d5ac-11eb-8210-b796de2aa556.png)

**Comment by andreifilip123** [comment]
I'll take this 👌
