### ISSUE TITLE
Create Static page component

### ISSUE THREAD

**Issue by catileptic** [code4romania/teacher-workout-client#8]
[The Figma document](https://www.figma.com/file/uLiqrlxmOB5xCppIzmiUXV/Teacher-Workout?node-id=1%3A2) contains the entire UI of the project. 

You can export any image (asset) directly from Figma. [Here's how](https://drive.google.com/file/d/1KJncuAGFvKEo6zrjC9H3O59auITE0q2h/view). 

**Please be mindful of the mobile layout as well. Try to use only Tailwind CSS for styling.**

If you want to work on this Issue, please leave a comment saying you're taking it <3 . 

---

This Component will be instantiated multiple times, in order to create the **Terms & Conditions** page, the **About** page, the **Cookie Policy** page. 

![image](https://user-images.githubusercontent.com/14028425/123399082-e059ba00-d5ac-11eb-994f-fb4ae1c5d6e1.png)

**Comment by crisan-catalin** [comment]
I will take it.
