### ISSUE TITLE
Create the admin navbar

### ISSUE THREAD

**Issue by radubuciuceanu** [code4romania/teacher-workout-client#81]
## About

- A navigation bar 
- It's gonna be used further by the admin layout 
- Zero functionality should be implemented at this moment (the layout only) 
- The tabs should not render anything (just some dummy tabs)

![image](https://user-images.githubusercontent.com/39530866/131041113-0f6fc5ee-d722-417d-b9d7-11e3e1152cf5.png)

## Designs

- [figma](https://www.figma.com/file/uLiqrlxmOB5xCppIzmiUXV/Teacher-Workout?node-id=625%3A2474)

**Comment by bogdanterzea** [comment]
I will do this layout today :D
CC: @RaduBuciuceanu @catileptic

**Comment by paradoxministry** [comment]
@bogdanterzea This ticket is unblocked.

**Comment by surdu** [comment]
@paradoxministry Have you done anything on this, or do you plan do still work on it ?

**Comment by catileptic** [comment]
Handing this issue over to @surdu
