### ISSUE TITLE
Create the admin dashboard card

### ISSUE THREAD

**Issue by radubuciuceanu** [code4romania/teacher-workout-client#83]
## About

- A reusable component 
- It's gonna be used by our dashboard page to render the statistics
- Do not use it yet

![image](https://user-images.githubusercontent.com/39530866/131041918-bed77f7e-e2f5-4cc9-89a3-e2abaa1d96f9.png)

## Designs

- [figma](https://www.figma.com/file/uLiqrlxmOB5xCppIzmiUXV/Teacher-Workout?node-id=625%3A2474)

**Comment by kata-kas** [comment]
Hello! I now realise that I have to build this first, in order to make the dashboard, so I'll make this first quickly.
