### ISSUE TITLE
Create the admin dashboard page

### ISSUE THREAD

**Issue by radubuciuceanu** [code4romania/teacher-workout-client#84]
## About

> This issue is blocked by the #83 and #82 ones.

- Create the dashboard page
- Configure the dashboard tab to render the page
- Setup all the cards with some dummy data
- Make sure to handle the responsiveness
- Make sure to handle the background image

![image](https://user-images.githubusercontent.com/39530866/131042156-cc6afc54-d77b-4027-b1b7-5d3e8d7d6191.png)

## Related

- [figma](https://www.figma.com/file/uLiqrlxmOB5xCppIzmiUXV/Teacher-Workout?node-id=625%3A2474)

**Comment by kata-kas** [comment]
Hello! I'll take this one next
