### ISSUE TITLE
Create the admin lessons page

### ISSUE THREAD

**Issue by radubuciuceanu** [code4romania/teacher-workout-client#85]
## About

> This issue is blocked by the #83 and #82 ones.

- A page that's gonna contain all the lessons
- Make it to be rendered under the _Lisa lectii_ tab
- Do not create any logic yet (only the layout)
- Use dummy data for the layout
- Make sure to handle the responsiveness
- Make sure to handle the background image
- Make sure to handle pagination

![image](https://user-images.githubusercontent.com/39530866/131042900-7e59260b-3638-459a-a1c2-4da6db2103a8.png)

## Designs

- [figma](https://www.figma.com/file/uLiqrlxmOB5xCppIzmiUXV/Teacher-Workout?node-id=625%3A2556)

**Comment by paradoxministry** [comment]
Taking this issue on.
CC @RaduBuciuceanu

**Comment by surdu** [comment]
@paradoxministry Have you done anything on this, or do you plan do still work on it ?

**Comment by paradoxministry** [comment]
@surdu I made a little progress but something came up and I don't have the time to complete the page any time soon. I would appreciate it if you could take it on.

**Comment by catileptic** [comment]
Handing this issue over to @surdu

**Comment by radubuciuceanu** [comment]
Taking this one.
