### ISSUE TITLE
Create the admin users page

### ISSUE THREAD

**Issue by radubuciuceanu** [code4romania/teacher-workout-client#87]
## About

> This issue is blocked by the #83 and #82 ones.

- A page used to manage all the users
- Make it to be rendered under the _Utilizatori_ tab
- Do not create any logic yet (only the layout)
- Use dummy data for the layout
- Make sure to handle the responsiveness
- Make sure to handle the background image
- Make sure to handle pagination

![image](https://user-images.githubusercontent.com/39530866/131043247-06e4fcbc-2141-4cfb-af35-0a3a30f64504.png)

## Designs 

- [figma](https://www.figma.com/file/uLiqrlxmOB5xCppIzmiUXV/Teacher-Workout?node-id=625%3A2711)

**Comment by andreifilip123** [comment]
This issue, along with #86 , #85 use the same datatable. I will make a shared component for it and make a PR

**Comment by radubuciuceanu** [comment]
This one will be taken by me.
