### ISSUE TITLE
Create Course listing page

### ISSUE THREAD

**Issue by catileptic** [code4romania/teacher-workout-client#9]
[The Figma document](https://www.figma.com/file/uLiqrlxmOB5xCppIzmiUXV/Teacher-Workout?node-id=1%3A2) contains the entire UI of the project. 

You can export any image (asset) directly from Figma. [Here's how](https://drive.google.com/file/d/1KJncuAGFvKEo6zrjC9H3O59auITE0q2h/view). 

**Please be mindful of the mobile layout as well. Try to use only Tailwind CSS for styling.**

If you want to work on this Issue, please leave a comment saying you're taking it <3 . 

---
There should be a Course Preview component, re-used throughout this page. The number of courses per page should be configurable. 

![image](https://user-images.githubusercontent.com/14028425/123399304-231b9200-d5ad-11eb-964c-4ee3682697c9.png)

**Comment by miutamihai** [comment]
I'll be taking this :+1:

**Comment by catileptic** [comment]
After a discussion with @miutamihai we decided to have a page that lists all the lesson themes and then the user can access a theme to see the list of lessons within that theme. 

Having a page that lists all lessons in all themes could end up creating a pretty big query and there isn't much reason to optimize around this use case
